version: '3'

services:
  api:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev

  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=api-rest-ts
    ports:
      - '27017:27017'