version: '3'

services:
  api:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - PORT=3002
      - DB_URI=mongodb://database:27017/api-rest-ts
    ports:
      - 3002:3002
    links:
      - database
    depends_on:
      - database
    networks:
      - node-database
    

  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=api-rest-ts
    ports:
      - '27017:27017'
    networks:
      - node-database

networks:
  node-database:
    driver: bridge